# Generated by Django 2.2.2 on 2019-06-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinphoto', models.ImageField(upload_to='media/')),
                ('pindate', models.DateTimeField(auto_now_add=True)),
                ('pinvisiteddate', models.DateTimeField()),
                ('pinbody', models.TextField()),
                ('pinuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
