# Generated by Django 2.2.2 on 2019-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pindrop',
            name='pinphoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
