# Generated by Django 2.2.2 on 2019-06-18 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0002_auto_20190613_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pindrop',
            name='pinlocation',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
