# Generated by Django 2.2.2 on 2019-06-18 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0003_pindrop_pinlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pindrop',
            name='pinlocation',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
