# Generated by Django 2.2.2 on 2019-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0004_auto_20190618_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pindrop',
            name='pinphoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/pinphotos/'),
        ),
    ]
