# Generated by Django 2.2.2 on 2019-06-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0006_auto_20190622_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pindrop',
            name='pinuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpin', to=settings.AUTH_USER_MODEL),
        ),
    ]
