# Generated by Django 2.2.2 on 2019-06-25 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogram', '0007_auto_20190622_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_type', models.CharField(max_length=17)),
                ('name', models.CharField(max_length=36)),
                ('abbrev', models.CharField(max_length=13)),
                ('formal_name', models.CharField(max_length=52)),
                ('pop_est', models.BigIntegerField()),
                ('gdp_md_est', models.FloatField()),
                ('pop_year', models.IntegerField()),
                ('lastcensus', models.IntegerField()),
                ('gdp_year', models.IntegerField()),
                ('continent', models.CharField(max_length=23)),
                ('region_un', models.CharField(max_length=23)),
                ('region_wb', models.CharField(max_length=26)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
